### GET root
GET http://127.0.0.1:3000 HTTP/1.1

### GET items
GET http://127.0.0.1:3000/items HTTP/1.1

### GET item
GET http://127.0.0.1:3000/items/1 HTTP/1.1

### POST item
POST http://127.0.0.1:3000/items/ HTTP/1.1
Content-Type: application/json

{
    "name": "New Item"
}

### DELETE item
DELETE http://127.0.0.1:3000/items/1 HTTP/1.1

### UPDATE item
PUT http://127.0.0.1:3000/items/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item"
}

### Auth Join
POST http://127.0.0.1:3000/auth/join HTTP/1.1
Content-Type: application/json

{
    "username": "usernamer",
    "password": "passwordr",
    "email": "emaili@emailr.com",
    "fullName": "fullnameor"
}

### Auth Login
POST http://127.0.0.1:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}